/**
 * Dashboard API Route
 * 
 * Returns comprehensive GEO Health Score and all component metrics.
 * Uses Chimera GEO SDK v2.0 for enhanced analysis.
 * 
 * @module api/dashboard
 */

import { NextResponse } from 'next/server';
import type {
  DashboardData,
  RouteHealthMetrics,
  ContentScannabilityMetrics,
  SchemaCoverageMetrics,
  HallucinationEntry,
  AgentType
} from '@/types';
import { calculateGEOScore, getCitations, calculateCitationAuthority } from '@/lib/citation-monitor';
import { getHallucinationLog } from '@/lib/hallucination-logger';
import { getAliases } from '@/lib/alias-manager';
// SDK available: import { createChimeraSDK } from '@/lib/sdk';

/**
 * Calculate route health metrics
 */
function calculateRouteHealth(): RouteHealthMetrics {
  const log = getHallucinationLog();
  const aliases = getAliases();
  
  const total404sCaught = log.length;
  const successfulRedirects = log.filter(e => e.outcome === 'redirected' || e.outcome === 'alias-used').length;
  const learnedAliases = aliases.filter(a => a.autoGenerated).length;
  
  const confidences = log.filter(e => e.confidence > 0).map(e => e.confidence);
  const averageConfidence = confidences.length > 0
    ? confidences.reduce((a, b) => a + b, 0) / confidences.length
    : 0;
  
  return {
    total404sCaught,
    successfulRedirects,
    learnedAliases,
    averageConfidence: Math.round(averageConfidence * 100) / 100
  };
}

/**
 * Calculate route health score (0-100)
 */
function calculateRouteHealthScore(metrics: RouteHealthMetrics): number {
  if (metrics.total404sCaught === 0) return 100;
  
  const redirectRate = metrics.successfulRedirects / metrics.total404sCaught;
  const confidenceBonus = metrics.averageConfidence * 20;
  
  return Math.min(Math.round(redirectRate * 80 + confidenceBonus), 100);
}

/**
 * Calculate content scannability metrics (mock for demo)
 */
function calculateContentScannability(): ContentScannabilityMetrics {
  // In production, would scan all content files
  return {
    averageScore: 0.65,
    pagesAnalyzed: 12,
    lowScorePages: ['/about', '/contact']
  };
}

/**
 * Calculate schema coverage metrics (mock for demo)
 */
function calculateSchemaCoverage(): SchemaCoverageMetrics {
  // In production, would scan all pages for JSON-LD
  return {
    coveragePercentage: 75,
    pagesWithSchema: 9,
    totalPages: 12,
    missingSchemaPages: ['/about', '/contact', '/privacy']
  };
}

/**
 * Calculate AI traffic summary
 */
function calculateAITrafficSummary(log: HallucinationEntry[]): {
  totalAIVisits: number;
  byAgentType: Record<AgentType, number>;
  humanVisits: number;
} {
  const byAgentType: Record<AgentType, number> = {
    'ChatGPT': 0,
    'Perplexity': 0,
    'Claude': 0,
    'Gemini': 0,
    'Bing': 0,
    'Generic-Bot': 0,
    'Human': 0
  };
  
  for (const entry of log) {
    byAgentType[entry.agentType] = (byAgentType[entry.agentType] || 0) + 1;
  }
  
  const humanVisits = byAgentType['Human'];
  const totalAIVisits = log.length - humanVisits;
  
  return {
    totalAIVisits,
    byAgentType,
    humanVisits
  };
}

/**
 * GET /api/dashboard
 * 
 * Returns complete dashboard data including GEO Health Score and all metrics.
 */
export async function GET() {
  try {
    // Calculate all metrics
    const routeHealthMetrics = calculateRouteHealth();
    const contentScannabilityMetrics = calculateContentScannability();
    const schemaCoverageMetrics = calculateSchemaCoverage();
    
    // Calculate citation authority
    const citations = getCitations();
    const citationAuthority = calculateCitationAuthority(citations);
    
    // Calculate GEO Health Score
    const geoHealthScore = calculateGEOScore({
      routeHealth: calculateRouteHealthScore(routeHealthMetrics),
      contentScannability: Math.round(contentScannabilityMetrics.averageScore * 100),
      schemaCoverage: schemaCoverageMetrics.coveragePercentage,
      citationAuthority
    });
    
    // Get recent hallucinations
    const hallucinationLog = getHallucinationLog();
    const recentHallucinations = hallucinationLog.slice(-10).reverse();
    
    // Calculate AI traffic summary
    const aiTrafficSummary = calculateAITrafficSummary(hallucinationLog);
    
    const dashboardData: DashboardData = {
      geoHealthScore,
      routeHealth: routeHealthMetrics,
      contentScannability: contentScannabilityMetrics,
      schemaCoverage: schemaCoverageMetrics,
      recentHallucinations,
      aiTrafficSummary
    };
    
    // Add SDK version info
    return NextResponse.json({
      ...dashboardData,
      sdkVersion: '2.0',
      sdkFeatures: [
        'Multi-algorithm fuzzy matching',
        'Information gain analysis',
        'Inverted pyramid scoring',
        'E-E-A-T schema generation',
        'Freshness monitoring',
        'Content transformation',
        'Engine-specific optimization'
      ]
    });
  } catch (error) {
    console.error('Dashboard API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch dashboard data' },
      { status: 500 }
    );
  }
}
