/**
 * Chimera: AI-First Edge - Core Type Definitions
 * 
 * These types define the contracts between all system components
 * as specified in the design document.
 */

// =============================================================================
// Agent Detection Types
// =============================================================================

export type AgentType = 
  | 'ChatGPT' 
  | 'Perplexity' 
  | 'Claude' 
  | 'Gemini' 
  | 'Bing'
  | 'Generic-Bot' 
  | 'Human';

export interface AgentSignature {
  type: AgentType;
  patterns: RegExp[];
  description: string;
}

export interface AgentDetectionResult {
  type: AgentType;
  confidence: number;
  signals: string[];
}

// =============================================================================
// Symbiote Router Types
// =============================================================================

export interface SymbioteRouterConfig {
  confidenceThreshold: number;      // Minimum similarity score (default: 0.7)
  maxLatencyMs: number;             // Maximum added latency (default: 100)
  enableLearning: boolean;          // Auto-create aliases
  aliasThreshold: number;           // Redirects before creating alias (default: 3)
}

export interface RouteMatch {
  originalPath: string;
  matchedPath: string;
  confidence: number;
  method: 'alias' | 'semantic' | 'none';
  latencyMs: number;
}

export interface SemanticMatch {
  route: string;
  confidence: number;
  matchedTokens: string[];
  reasoning: string;
}

// =============================================================================
// Alias System Types
// =============================================================================

export interface Alias {
  id: string;
  fromPath: string;               // Hallucinated path
  toPath: string;                 // Valid destination
  hitCount: number;               // Times used
  createdAt: Date;
  lastUsedAt: Date;
  autoGenerated: boolean;         // Created by learning system
}

export interface AliasStore {
  aliases: Alias[];
  redirectCounts: Record<string, number>; // Track counts before alias creation
}

// =============================================================================
// Hallucination Logging Types
// =============================================================================

export interface HallucinationEntry {
  id: string;
  timestamp: Date;
  hallucinatedPath: string;
  matchedPath: string | null;
  confidence: number;
  agentType: AgentType;
  outcome: 'redirected' | '404' | 'alias-used';
  latencyMs: number;
}

// =============================================================================
// Analytics Types
// =============================================================================

export interface AnalyticsRecord {
  id: string;
  timestamp: Date;
  path: string;
  agentType: AgentType;
  wasRedirected: boolean;
  sessionId: string;
  conversionEvent: string | null;
}

// =============================================================================
// Fact-Density Analyzer Types
// =============================================================================

export type JustificationLevel = 'high' | 'medium' | 'low';

export type SuggestionType = 
  | 'add-table' 
  | 'add-stats' 
  | 'fix-headers' 
  | 'reduce-fluff'
  | 'add-list';

export interface ContentBreakdown {
  tables: number;
  bulletLists: number;
  statistics: number;
  headers: number;
  headerHierarchyValid: boolean;
  headerLevels: number[];
}

export interface Suggestion {
  type: SuggestionType;
  location: { line: number; column: number };
  message: string;
  autoFixAvailable: boolean;
}

export interface FactDensityResult {
  score: number;                    // 0-1 scannability score
  breakdown: ContentBreakdown;
  suggestions: Suggestion[];
  justificationLevel: JustificationLevel;
}

// =============================================================================
// Schema Generator Types
// =============================================================================

export type SchemaEntityType = 
  | 'Product' 
  | 'Article' 
  | 'Organization' 
  | 'Person' 
  | 'FAQ'
  | 'WebPage'
  | 'BreadcrumbList'
  | 'HowTo';

export interface DetectedEntity {
  type: SchemaEntityType;
  name: string;
  description?: string;
  properties: Record<string, unknown>;
  confidence: number;
}

export interface SchemaEntity {
  '@type': string;
  '@id'?: string;
  [key: string]: unknown;
}

export interface GeneratedSchema {
  '@context': 'https://schema.org';
  '@graph': SchemaEntity[];
}

export interface SchemaValidationError {
  entityType: string;
  property: string;
  message: string;
  severity: 'error' | 'warning';
}

export interface SchemaValidationResult {
  valid: boolean;
  errors: SchemaValidationError[];
}

// =============================================================================
// Citation Monitor Types
// =============================================================================

export type Sentiment = 'positive' | 'neutral' | 'negative';

export interface Citation {
  id: string;
  sourceUrl: string;
  sourceDomain: string;
  mentionContext: string;
  sentiment: Sentiment;
  domainAuthority: number;
  discoveredAt: Date;
  isEarnedMedia: boolean;
}

export interface CitationMonitorConfig {
  brandTerms: string[];
  searchApiKey?: string;
  scanIntervalHours: number;
}

// =============================================================================
// GEO Health Score Types
// =============================================================================

export interface GEOHealthComponents {
  routeHealth: number;
  contentScannability: number;
  schemaCoverage: number;
  citationAuthority: number;
}

export interface GEOHealthScore {
  overall: number;                  // 0-100
  components: GEOHealthComponents;
  recommendations: string[];
  calculatedAt: Date;
}

export interface RouteHealthMetrics {
  total404sCaught: number;
  successfulRedirects: number;
  learnedAliases: number;
  averageConfidence: number;
}

export interface ContentScannabilityMetrics {
  averageScore: number;
  pagesAnalyzed: number;
  lowScorePages: string[];
}

export interface SchemaCoverageMetrics {
  coveragePercentage: number;
  pagesWithSchema: number;
  totalPages: number;
  missingSchemaPages: string[];
}

// =============================================================================
// Topic Mapper Types
// =============================================================================

export interface PageNode {
  path: string;
  title: string;
  contentHash: string;
}

export interface PageRelationship {
  sourcePath: string;
  targetPath: string;
  similarity: number;
  sharedTopics: string[];
}

export interface TopicCluster {
  id: string;
  name: string;
  pages: string[];
  centralPage: string;
}

export interface TopicMapResult {
  nodes: PageNode[];
  relationships: PageRelationship[];
  clusters: TopicCluster[];
  orphanPages: string[];
}

export interface LinkingSuggestion {
  fromPath: string;
  toPath: string;
  reason: string;
  priority: 'high' | 'medium' | 'low';
}

// =============================================================================
// Sitemap Types
// =============================================================================

export interface SitemapEntry {
  loc: string;
  lastmod?: string;
  changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority?: number;
}

export interface SitemapIndex {
  sitemaps: string[];
}

// =============================================================================
// Content Analysis Cache Types
// =============================================================================

export interface ContentAnalysis {
  filePath: string;
  lastAnalyzed: Date;
  factDensityScore: number;
  schemaGenerated: boolean;
  suggestions: Suggestion[];
}

// =============================================================================
// Dashboard API Response Types
// =============================================================================

export interface DashboardData {
  geoHealthScore: GEOHealthScore;
  routeHealth: RouteHealthMetrics;
  contentScannability: ContentScannabilityMetrics;
  schemaCoverage: SchemaCoverageMetrics;
  recentHallucinations: HallucinationEntry[];
  aiTrafficSummary: {
    totalAIVisits: number;
    byAgentType: Record<AgentType, number>;
    humanVisits: number;
  };
}
